arrowParens: always
bracketSpacing: true
printWidth: 100
semi: true
singleQuote: true
tabWidth: 4
trailingComma: es5
useTabs: true

overrides:
    - files: '*.yaml'
      options:
          tabWidth: 4
          useTabs: false
    - files: '*.json'
      options:
          tabWidth: 2
          useTabs: false
